<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseIntermediateOutputPath>..\..\.tmp\PolicyChecks\obj\</BaseIntermediateOutputPath>
    <BaseOutputPath>..\..\.tmp\PolicyChecks\bin\</BaseOutputPath>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MasterApp\MasterApp.csproj" />
  </ItemGroup>

</Project>
